name: Publish

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Modify PowerShell Policy
        run: Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Force
          
      - name: Install .NET
        run: |
          .\res\build\dotnet-install.ps1 -Channel 5.0
          .\res\build\dotnet-install.ps1 -Channel 3.1
          
      - name: Checkout
        uses: actions/checkout@v2

      - name: NuGet (Release)
        run: .\res\build\nuget.ps1 -ApiKey ${{ secrets.NUGET_KEY }}
        if: "!github.event.release.prerelease"
        
      - name: Nuget (Beta)
        run: .\res\build\nuget.ps1 -ApiKey ${{ secrets.NUGET_KEY }} -Suffix "-beta"
        if: "github.event.release.prerelease"